/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : string,
  'text' : string,
  'classId' : string,
  'sentAt' : Time,
  'senderName' : string,
  'senderId' : Principal,
}
export interface Class {
  'id' : string,
  'status' : ClassStatus,
  'title' : string,
  'subject' : Subject,
  'scheduledTime' : Time,
  'createdAt' : Time,
  'description' : string,
  'teacherId' : Principal,
}
export type ClassStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'ended' : null };
export type ExternalBlob = Uint8Array;
export interface Profile {
  'bio' : string,
  'subject' : [] | [Subject],
  'name' : string,
  'isTeacher' : boolean,
}
export interface Recording {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'blob' : ExternalBlob,
  'classId' : string,
  'uploadedAt' : Time,
  'uploadedBy' : Principal,
}
export type Subject = { 'other' : string } |
  { 'math' : null } |
  { 'history' : null } |
  { 'english' : null } |
  { 'science' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[string, string, Subject, Time], string>,
  'deleteClass' : ActorMethod<[string], undefined>,
  'enrollInClass' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getClass' : ActorMethod<[string], Class>,
  'getClassEnrollees' : ActorMethod<[string], Array<Principal>>,
  'getClasses' : ActorMethod<[], Array<Class>>,
  'getRecording' : ActorMethod<[string], Recording>,
  'getRecordings' : ActorMethod<[], Array<Recording>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendChatMessage' : ActorMethod<[string, string], string>,
  'uploadRecording' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];