/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({
  'other' : IDL.Text,
  'math' : IDL.Null,
  'history' : IDL.Null,
  'english' : IDL.Null,
  'science' : IDL.Null,
});
export const Time = IDL.Int;
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'subject' : IDL.Opt(Subject),
  'name' : IDL.Text,
  'isTeacher' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'classId' : IDL.Text,
  'sentAt' : Time,
  'senderName' : IDL.Text,
  'senderId' : IDL.Principal,
});
export const ClassStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'ended' : IDL.Null,
});
export const Class = IDL.Record({
  'id' : IDL.Text,
  'status' : ClassStatus,
  'title' : IDL.Text,
  'subject' : Subject,
  'scheduledTime' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'teacherId' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Recording = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'blob' : ExternalBlob,
  'classId' : IDL.Text,
  'uploadedAt' : Time,
  'uploadedBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([IDL.Text, IDL.Text, Subject, Time], [IDL.Text], []),
  'deleteClass' : IDL.Func([IDL.Text], [], []),
  'enrollInClass' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getClass' : IDL.Func([IDL.Text], [Class], ['query']),
  'getClassEnrollees' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getRecording' : IDL.Func([IDL.Text], [Recording], ['query']),
  'getRecordings' : IDL.Func([], [IDL.Vec(Recording)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'uploadRecording' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'other' : IDL.Text,
    'math' : IDL.Null,
    'history' : IDL.Null,
    'english' : IDL.Null,
    'science' : IDL.Null,
  });
  const Time = IDL.Int;
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'subject' : IDL.Opt(Subject),
    'name' : IDL.Text,
    'isTeacher' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'classId' : IDL.Text,
    'sentAt' : Time,
    'senderName' : IDL.Text,
    'senderId' : IDL.Principal,
  });
  const ClassStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'ended' : IDL.Null,
  });
  const Class = IDL.Record({
    'id' : IDL.Text,
    'status' : ClassStatus,
    'title' : IDL.Text,
    'subject' : Subject,
    'scheduledTime' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'teacherId' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Recording = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'blob' : ExternalBlob,
    'classId' : IDL.Text,
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func(
        [IDL.Text, IDL.Text, Subject, Time],
        [IDL.Text],
        [],
      ),
    'deleteClass' : IDL.Func([IDL.Text], [], []),
    'enrollInClass' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getClass' : IDL.Func([IDL.Text], [Class], ['query']),
    'getClassEnrollees' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getRecording' : IDL.Func([IDL.Text], [Recording], ['query']),
    'getRecordings' : IDL.Func([], [IDL.Vec(Recording)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'uploadRecording' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };